// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehiclesRenting.Data;

#nullable disable

namespace VehiclesRenting.Data.Migrations
{
    [DbContext(typeof(VehiclesRentingDbContext))]
    [Migration("20230702123849_SetCategoryIdToDefaultForEntity")]
    partial class SetCategoryIdToDefaultForEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("RenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RenterId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16c47ced-2fd4-4ffc-8769-06e4e8059e8f"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "Hyundai",
                            CategoryId = 0,
                            Color = "Black",
                            CreatedOn = new DateTime(2023, 7, 2, 12, 38, 47, 569, DateTimeKind.Utc).AddTicks(6369),
                            CurrentAddress = "Silistra, Center",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/4b/Hyundai_Santa_Fe_%28TM%29_PHEV_FL_IMG_6648.jpg",
                            Model = "Santa fe",
                            PricePerDay = 40m,
                            RegistrationNumber = "CC1835AX",
                            RenterId = new Guid("c42ef5d1-0c67-4dc2-9467-ec9947baa83f")
                        },
                        new
                        {
                            Id = new Guid("40b74307-95ec-41d2-8ff1-c879006a171b"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "Mercedes",
                            CategoryId = 0,
                            Color = "White",
                            CreatedOn = new DateTime(2023, 7, 2, 12, 38, 47, 569, DateTimeKind.Utc).AddTicks(6573),
                            CurrentAddress = "Silistra, Center",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Mercedes-Benz_W223_IMG_6663.jpg/1200px-Mercedes-Benz_W223_IMG_6663.jpg",
                            Model = "S-Class",
                            PricePerDay = 70m,
                            RegistrationNumber = "CB0832AP"
                        },
                        new
                        {
                            Id = new Guid("c02247bc-1488-4191-a47f-9d4aa1f6a26a"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "Ford Mustang",
                            CategoryId = 0,
                            Color = "Gray",
                            CreatedOn = new DateTime(2023, 7, 2, 12, 38, 47, 569, DateTimeKind.Utc).AddTicks(6582),
                            CurrentAddress = "Silistra, East",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/f/f6/1967_Ford_Mustang_Shelby_GT-500_Eleanor.jpg",
                            Model = "GT500 Shelby",
                            PricePerDay = 200m,
                            RegistrationNumber = "CC0000CC"
                        });
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Car"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Motorcycle"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Yacht"
                        });
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Jet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("RenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RenterId");

                    b.ToTable("Jets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("190cfb6a-7efa-411a-8bc2-847541cf1854"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "Yamaha",
                            CategoryId = 0,
                            Color = "Black",
                            CreatedOn = new DateTime(2023, 7, 2, 15, 38, 47, 570, DateTimeKind.Local).AddTicks(4209),
                            CurrentAddress = "Varna, Black Sea",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/7/7d/2020_Yamaha_FX_SVHO_WaveRunner.jpg",
                            Model = "Wave Runner",
                            PricePerDay = 50m,
                            RenterId = new Guid("c42ef5d1-0c67-4dc2-9467-ec9947baa83f")
                        },
                        new
                        {
                            Id = new Guid("18fff1a9-06cd-4b63-8c50-19f1332e093a"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "Honda",
                            CategoryId = 0,
                            Color = "Red",
                            CreatedOn = new DateTime(2023, 7, 2, 15, 38, 47, 570, DateTimeKind.Local).AddTicks(4349),
                            CurrentAddress = "Burgas",
                            ImageUrl = "https://getmyboat-user-images1.imgix.net/images/626ebcd126768/-processed.jpg",
                            Model = "PWC",
                            PricePerDay = 60m
                        },
                        new
                        {
                            Id = new Guid("975e1497-71f3-4e98-acee-9371878ea77c"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "Yamaha",
                            CategoryId = 0,
                            Color = "Blue",
                            CreatedOn = new DateTime(2023, 7, 2, 15, 38, 47, 570, DateTimeKind.Local).AddTicks(4364),
                            CurrentAddress = "Balchik",
                            ImageUrl = "https://d1kqllve43agrl.cloudfront.net/imgs/Yamaha-superjet-701-bj-2008-17754.jpeg",
                            Model = "Superjet 701",
                            PricePerDay = 45m
                        });
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Motorcycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("RenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RenterId");

                    b.ToTable("Motorcycles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8348303b-638e-4095-a431-9b17dfa109eb"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "Honda",
                            CategoryId = 0,
                            Color = "Red",
                            CreatedOn = new DateTime(2023, 7, 2, 12, 38, 47, 571, DateTimeKind.Utc).AddTicks(1254),
                            CurrentAddress = "Ruse, Center",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Honda750NR.jpg/1200px-Honda750NR.jpg",
                            Model = "NR-L",
                            PricePerDay = 30m,
                            RegistrationNumber = "CC3552OB",
                            RenterId = new Guid("c42ef5d1-0c67-4dc2-9467-ec9947baa83f")
                        },
                        new
                        {
                            Id = new Guid("48657c2e-adcf-461c-9c37-3af9d28d811b"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "Suzuki",
                            CategoryId = 0,
                            Color = "Blue",
                            CreatedOn = new DateTime(2023, 7, 2, 12, 38, 47, 571, DateTimeKind.Utc).AddTicks(1298),
                            CurrentAddress = "Silistra, Center",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/GSXR1000K5.jpg/640px-GSXR1000K5.jpg",
                            Model = "GSX-R1000K5",
                            PricePerDay = 75m,
                            RegistrationNumber = "CC1550AB"
                        },
                        new
                        {
                            Id = new Guid("afaee2d6-a456-4bbe-b607-d2ee4cbb7b0f"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "Harley-Davidson",
                            CategoryId = 0,
                            Color = "Gray",
                            CreatedOn = new DateTime(2023, 7, 2, 12, 38, 47, 571, DateTimeKind.Utc).AddTicks(1303),
                            CurrentAddress = "Silistra, West",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/1/13/Harley_5-06.jpg",
                            Model = "VRSC",
                            PricePerDay = 110m,
                            RegistrationNumber = "CC1200AK"
                        });
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Scooter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("RenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RenterId");

                    b.ToTable("Scooters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("239e20a6-ed19-4537-97ce-9cecf8ca6181"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "Xiomi",
                            CategoryId = 0,
                            CreatedOn = new DateTime(2023, 7, 2, 12, 38, 47, 571, DateTimeKind.Utc).AddTicks(8014),
                            CurrentAddress = "Silistra, Center",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Xiaomi_M365.jpg/1200px-Xiaomi_M365.jpg",
                            PricePerDay = 12m,
                            RenterId = new Guid("c42ef5d1-0c67-4dc2-9467-ec9947baa83f")
                        },
                        new
                        {
                            Id = new Guid("81b1c074-cb07-4435-9ba4-b8b706c26494"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "E-scooter",
                            CategoryId = 0,
                            CreatedOn = new DateTime(2023, 7, 2, 12, 38, 47, 571, DateTimeKind.Utc).AddTicks(8057),
                            CurrentAddress = "Silistra, North",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Elektrische-tretroller.jpg/800px-Elektrische-tretroller.jpg",
                            PricePerDay = 7m
                        },
                        new
                        {
                            Id = new Guid("90f56177-1cec-4056-acb2-f5dfe2015d36"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "Inmotion",
                            CategoryId = 0,
                            CreatedOn = new DateTime(2023, 7, 2, 12, 38, 47, 571, DateTimeKind.Utc).AddTicks(8062),
                            CurrentAddress = "Silistra, West",
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0021/7389/4702/products/LeMotion-Web-1.jpg?v=1636106454",
                            PricePerDay = 9m
                        });
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Yacht", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("RenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RenterId");

                    b.ToTable("Yachts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("78f07da5-775c-41cc-aa6f-2364a60dc5c6"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "Bavaria",
                            CategoryId = 0,
                            Color = "White",
                            CreatedOn = new DateTime(2023, 7, 2, 12, 38, 47, 572, DateTimeKind.Utc).AddTicks(4949),
                            CurrentAddress = "Varna",
                            ImageUrl = "https://images.boatsgroup.com/images/1/95/5/8289505_0_230720220750_1.jpg",
                            Model = "37 Sport",
                            PricePerDay = 200m,
                            RenterId = new Guid("c42ef5d1-0c67-4dc2-9467-ec9947baa83f")
                        },
                        new
                        {
                            Id = new Guid("e9f572e8-fcfd-498c-ae77-1426319c4e3e"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "Bavaria",
                            CategoryId = 0,
                            Color = "White",
                            CreatedOn = new DateTime(2023, 7, 2, 12, 38, 47, 572, DateTimeKind.Utc).AddTicks(4990),
                            CurrentAddress = "Burgas",
                            ImageUrl = "https://www.sailionian.com/wp-content/uploads/2020/05/c42-ex-01.jpg",
                            Model = "C42 Freedom",
                            PricePerDay = 220m
                        },
                        new
                        {
                            Id = new Guid("235b8d48-01ec-4091-9c87-0c5aea367e50"),
                            AgentId = new Guid("8ed4eaa3-738c-49a4-9cf8-874903ded0bb"),
                            Brand = "Hanse",
                            CategoryId = 0,
                            Color = "Gray",
                            CreatedOn = new DateTime(2023, 7, 2, 12, 38, 47, 572, DateTimeKind.Utc).AddTicks(4998),
                            CurrentAddress = "Varna",
                            ImageUrl = "https://img.yachtall.com/image-sale-boat/hanse-675-huge-203059a1l5rng9zti.jpg",
                            Model = "675",
                            PricePerDay = 180m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("VehiclesRenting.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("VehiclesRenting.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehiclesRenting.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("VehiclesRenting.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Agent", b =>
                {
                    b.HasOne("VehiclesRenting.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Car", b =>
                {
                    b.HasOne("VehiclesRenting.Data.Models.Agent", "Agent")
                        .WithMany("ManagedCars")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehiclesRenting.Data.Models.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehiclesRenting.Data.Models.User", "Renter")
                        .WithMany("RentedCars")
                        .HasForeignKey("RenterId");

                    b.Navigation("Agent");

                    b.Navigation("Category");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Jet", b =>
                {
                    b.HasOne("VehiclesRenting.Data.Models.Agent", "Agent")
                        .WithMany("ManagedJets")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehiclesRenting.Data.Models.Category", "Category")
                        .WithMany("Jets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehiclesRenting.Data.Models.User", "Renter")
                        .WithMany("RentedJets")
                        .HasForeignKey("RenterId");

                    b.Navigation("Agent");

                    b.Navigation("Category");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Motorcycle", b =>
                {
                    b.HasOne("VehiclesRenting.Data.Models.Agent", "Agent")
                        .WithMany("ManagedMotorcycles")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehiclesRenting.Data.Models.Category", "Category")
                        .WithMany("Motorcycles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehiclesRenting.Data.Models.User", "Renter")
                        .WithMany("RentedMotorcycles")
                        .HasForeignKey("RenterId");

                    b.Navigation("Agent");

                    b.Navigation("Category");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Scooter", b =>
                {
                    b.HasOne("VehiclesRenting.Data.Models.Agent", "Agent")
                        .WithMany("ManagedScooters")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehiclesRenting.Data.Models.Category", "Category")
                        .WithMany("Scooters")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehiclesRenting.Data.Models.User", "Renter")
                        .WithMany("RentedScooters")
                        .HasForeignKey("RenterId");

                    b.Navigation("Agent");

                    b.Navigation("Category");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Yacht", b =>
                {
                    b.HasOne("VehiclesRenting.Data.Models.Agent", "Agent")
                        .WithMany("ManagedYachts")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehiclesRenting.Data.Models.Category", "Category")
                        .WithMany("Yachts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehiclesRenting.Data.Models.User", "Renter")
                        .WithMany("RentedYachts")
                        .HasForeignKey("RenterId");

                    b.Navigation("Agent");

                    b.Navigation("Category");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Agent", b =>
                {
                    b.Navigation("ManagedCars");

                    b.Navigation("ManagedJets");

                    b.Navigation("ManagedMotorcycles");

                    b.Navigation("ManagedScooters");

                    b.Navigation("ManagedYachts");
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.Category", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Jets");

                    b.Navigation("Motorcycles");

                    b.Navigation("Scooters");

                    b.Navigation("Yachts");
                });

            modelBuilder.Entity("VehiclesRenting.Data.Models.User", b =>
                {
                    b.Navigation("RentedCars");

                    b.Navigation("RentedJets");

                    b.Navigation("RentedMotorcycles");

                    b.Navigation("RentedScooters");

                    b.Navigation("RentedYachts");
                });
#pragma warning restore 612, 618
        }
    }
}
